#include <bits/stdc++.h>
using namespace std;
int main(){
    int next_permutation;
    //FIRST CHECK FROM WHICH POINT THE A[i]<ARR[i+1] THEN AFTER FINDING THE I THEN YOU NEED TO FIND THE SMALLEST LARGE ELEMENT WHICH IS LARGE THEN THE INDEXX AND AFTER THAT 
    //REVERSE THE ARRAY FROM THE A.BEGIN()+INDEXX TO THE LAST INDEX 
}